Add companion object to both Aggregation and Query
lambdaworks/zio-elasticsearch pull request #126
Opened 2023-03-24 11:29 UTC by dbulaja98

2023-03-24 15:08 UTC, markaya requested changes

2023-03-24 15:08 UTC, markaya commented on modules/library/src/main/scala/zio/elasticsearch/aggregation/Aggregation.scala
> +      }
maybe to use here:
`currSubAggs match  {
    case Nil => 
    ...
    case _ =>
     ...
}`

2023-03-26 12:08 UTC, drmarjanovic requested changes

2023-03-26 12:08 UTC, drmarjanovic commented on modules/library/src/main/scala/zio/elasticsearch/query/Query.scala
> +sealed trait Query[-S] { self =>
Let's keep `ElasticQuery` as the public name.

2023-03-27 08:24 UTC, dbulaja98 commented on modules/library/src/main/scala/zio/elasticsearch/aggregation/Aggregation.scala
> +      Obj(aggregations.map { case Terms(name, field, subAggregations) =>
`Scalafmt` returns it there.

2023-03-27 08:30 UTC, closed without merging