Support Script Sort
lambdaworks/zio-elasticsearch pull request #134
Opened 2023-03-28 08:49 UTC by dbulaja98

2023-03-28 20:48 UTC, drmarjanovic requested changes

2023-03-28 20:48 UTC, drmarjanovic commented on modules/library/src/main/scala/zio/elasticsearch/ElasticSort.scala
> +  def sortByField[S](field: Field[S, _]): SortByField =
Let's name it `sortBy`.

2023-03-28 20:48 UTC, drmarjanovic commented on modules/library/src/main/scala/zio/elasticsearch/ElasticSort.scala
> +  def sortByScript(script: String, sourceType: SourceType): SortByScript =
I would create `Script` as `AnyVal` or `Newtype`, and use `sortBy` here as well. 

```
sortBy(field: String, ...)
sortBy(script: Script, ...)
```

2023-03-28 20:48 UTC, drmarjanovic commented on modules/library/src/main/scala/zio/elasticsearch/query/sort/Sort.scala
> +        if (params.nonEmpty)
Let's add parentheses.

2023-03-29 07:11 UTC, arnoldlacko commented on modules/library/src/main/scala/zio/elasticsearch/query/sort/Sort.scala
> +        ).collect { case Some(obj) => obj }: _*
I think this `collect` could be `flatten`

2023-03-29 15:18 UTC, drmarjanovic approved these changes

2023-03-29 15:18 UTC, merged