Add `Scaladoc` to public API
lambdaworks/zio-elasticsearch pull request #160
Opened 2023-04-12 13:14 UTC by dbulaja98

Resolves #127

2023-04-19 09:11 UTC, drmarjanovic requested changes

2023-04-19 09:11 UTC, drmarjanovic commented on modules/library/src/main/scala/zio/elasticsearch/Elasticsearch.scala
> +   * Executes the given [[SearchRequest]] and emits the search results as a Stream.
Maybe: `Executes the given [[SearchRequest]] as a stream`?

2023-04-19 09:11 UTC, drmarjanovic commented on modules/library/src/main/scala/zio/elasticsearch/Elasticsearch.scala
> +   *   returns a Stream of [[Item]].
Maybe we can use `[[zio.Stream]]`?

2023-04-19 09:11 UTC, drmarjanovic commented on modules/library/src/main/scala/zio/elasticsearch/Elasticsearch.scala
> +   * Executes a [[SearchRequest]] with a given [[StreamConfig]] and emits the search results as a Stream.
Maybe to avoid return here.

2023-04-19 09:11 UTC, drmarjanovic commented on modules/library/src/main/scala/zio/elasticsearch/package.scala
> +     *   returns a `RIO` effect that, when executed, will produce an optional [[AggregationResponse]].
Maybe to add `RIO`.

2023-04-19 09:11 UTC, drmarjanovic commented on modules/library/src/main/scala/zio/elasticsearch/query/package.scala
> +     * Sets the `boost` parameter for this [[ElasticQuery]].
Maybe to describe what the boost is.

2023-04-19 09:11 UTC, drmarjanovic commented on modules/library/src/main/scala/zio/elasticsearch/query/package.scala
> +     *   a double `boost` value to set
Maybe to say `a non-negative real number...`

2023-04-19 09:11 UTC, drmarjanovic commented on modules/library/src/main/scala/zio/elasticsearch/query/package.scala
> +     * Sets the `caseInsensitive` parameter for this [[ElasticQuery]].
Maybe to describe what caseInsensitive parameter is.

2023-04-19 09:11 UTC, drmarjanovic commented on modules/library/src/main/scala/zio/elasticsearch/query/package.scala
> +     *   the `boolean` value for `caseInsensitive` parameter
Should we use `boolean`?

2023-04-19 09:11 UTC, drmarjanovic commented on modules/library/src/main/scala/zio/elasticsearch/query/package.scala
> +     *   the [[ScoreMode]] to use for this [[NestedQuery]]
Let's specify the `ScoreMode` options.

2023-04-19 09:11 UTC, drmarjanovic commented on modules/library/src/main/scala/zio/elasticsearch/request/package.scala
> +     *   the `Int` value to set the `from` parameter in the [[ElasticRequest]]
Maybe to use `a non-negative number to set...`

2023-04-19 09:11 UTC, drmarjanovic commented on modules/library/src/main/scala/zio/elasticsearch/request/package.scala
> +     *   returns a new instance of the [[ElasticRequest]] type with the `from` parameter set.
Maybe to use `an instance of the [[ElasticRequest]] enriched with the `from` parameter.

2023-04-19 09:11 UTC, drmarjanovic commented on modules/library/src/main/scala/zio/elasticsearch/request/package.scala
> +     * Sets the number of results to return.
I would say this is "the maximum number of results".

2023-04-19 09:11 UTC, drmarjanovic commented on modules/library/src/main/scala/zio/elasticsearch/request/package.scala
> +     *   the `Int` value to set the `size` parameter in the [[ElasticRequest]]
a non-negative number...

2023-04-19 19:09 UTC, drmarjanovic commented on modules/library/src/main/scala/zio/elasticsearch/query/sort/package.scala
> +     *   the [[SortMode]] used to pick a value among the sorted set of documents
```suggestion
     *   the [[SortMode]] used to pick a value among the sorted set of documents:
```

2023-04-19 19:11 UTC, drmarjanovic commented on modules/library/src/main/scala/zio/elasticsearch/request/package.scala
> +     *   `true` if the index be refreshed after the operation, `false` otherwise
"should be"?

2023-04-20 07:57 UTC, dbulaja98 commented on modules/library/src/main/scala/zio/elasticsearch/ElasticHighlight.scala
> +   *   an instance of [[Highlights]] with a chunk of [[HighlightField]].
I don't think so.

2023-04-20 09:29 UTC, drmarjanovic requested changes

2023-04-20 09:29 UTC, drmarjanovic commented on modules/library/src/main/scala/zio/elasticsearch/highlights/Highlights.scala
> +   * Sets `explicitFieldOrder` parameter to `true` in the [[Highlights]].
Can you explain this better?

2023-04-20 09:29 UTC, drmarjanovic commented on modules/library/src/main/scala/zio/elasticsearch/query/package.scala
> +     *   - [[ScoreMode.Avg]]: Use the mean relevance score of all matching child objects.
`Uses` or `Use`? Maybe to avoid `.` and capital letters here.

"uses the mean relevance score of all matching child objects"

2023-04-20 09:29 UTC, drmarjanovic commented on modules/library/src/main/scala/zio/elasticsearch/request/package.scala
> +     *   should be `true` if the index be refreshed after the operation, `false` otherwise
```suggestion
     *   should be `true` if the index should be refreshed after the executed operation, `false` otherwise
```

2023-04-20 11:17 UTC, dbulaja98 commented on modules/library/src/main/scala/zio/elasticsearch/ElasticQuery.scala
> +   * Constructs an instance of [[BoolQuery]] with queries that must satisfy the criteria using the specified parameters.
Scoring is ignored in `filter`.

2023-04-20 13:26 UTC, drmarjanovic requested changes

2023-04-20 13:26 UTC, drmarjanovic commented on modules/library/src/main/scala/zio/elasticsearch/ElasticQuery.scala
> +   * Constructs an instance of [[RangeQuery]] using the specified parameters.
Same here.

2023-04-20 13:26 UTC, drmarjanovic commented on modules/library/src/main/scala/zio/elasticsearch/ElasticQuery.scala
> +   * matching documents containing a value that contains, starts, or ends with the specified value in the specified
Maybe "that matches a provided pattern value". I think the Wildcard query works as a regex.

2023-04-20 13:26 UTC, drmarjanovic commented on modules/library/src/main/scala/zio/elasticsearch/ElasticQuery.scala
> +   * documents containing a value that contains, starts, or ends with the specified value in the specified field.
Same here.

2023-04-20 13:26 UTC, drmarjanovic commented on modules/library/src/main/scala/zio/elasticsearch/ElasticRequest.scala
> +   * Constructs an instance of [[DeleteByQueryRequest]] used for deleting documents from the specified index by
Maybe - deleting documents from the specified index that satisfy specified query

2023-04-20 13:26 UTC, drmarjanovic commented on modules/library/src/main/scala/zio/elasticsearch/ElasticRequest.scala
> +   *   a [[Script]] object containing the update logic to apply to all documents
```suggestion
   *   a [[Script]] object containing the update logic to apply
```

2023-04-20 13:26 UTC, drmarjanovic commented on modules/library/src/main/scala/zio/elasticsearch/ElasticRequest.scala
> +   * Constructs an instance of [[UpdateByQueryRequest]] used for updating documents matching specified query in the
Maybe "satisfy" instead of "match"?

2023-04-20 13:26 UTC, drmarjanovic commented on modules/library/src/main/scala/zio/elasticsearch/ElasticRequest.scala
> +   *   a [[Script]] object containing the update logic to apply to matching documents
```suggestion
   *   a [[Script]] object containing the update logic to apply
```

2023-04-20 13:26 UTC, drmarjanovic commented on modules/library/src/main/scala/zio/elasticsearch/highlights/Highlights.scala
> +   * highlight fields will be in the order they were specified
```suggestion
   * highlight fields will be in the order they were specified.
```

2023-04-20 13:26 UTC, drmarjanovic commented on modules/library/src/main/scala/zio/elasticsearch/query/package.scala
> +     *   - [[ScoreMode.Max]]: uses the highest relevance score of all matching child objects.
```suggestion
     *   - [[ScoreMode.Max]]: uses the highest relevance score of all matching child objects
```

2023-04-20 13:26 UTC, drmarjanovic commented on modules/library/src/main/scala/zio/elasticsearch/query/package.scala
> +     *   - [[ScoreMode.Min]]: uses the lowest relevance score of all matching child objects.
```suggestion
     *   - [[ScoreMode.Min]]: uses the lowest relevance score of all matching child objects
```

2023-04-20 13:26 UTC, drmarjanovic commented on modules/library/src/main/scala/zio/elasticsearch/query/package.scala
> +     *   - [[ScoreMode.Sum]]: adds together the relevance scores of all matching child objects.
```suggestion
     *   - [[ScoreMode.Sum]]: adds together the relevance scores of all matching child objects
```

2023-04-20 13:26 UTC, drmarjanovic commented on modules/library/src/main/scala/zio/elasticsearch/query/sort/package.scala
> +     *   the [[NumericType]] that should be used for sorting the field.
```suggestion
     *   the [[NumericType]] that should be used for sorting the field
```

2023-04-20 13:26 UTC, drmarjanovic commented on modules/library/src/main/scala/zio/elasticsearch/query/sort/package.scala
> +     *   - [[NumericType.Date]]: converts values do Date
Lines 76-79 - use `to` instead of `do`.

2023-04-20 13:26 UTC, drmarjanovic commented on modules/library/src/main/scala/zio/elasticsearch/query/sort/package.scala
> +     *   - [[SortOrder.Asc]]: sets Ascending sorting order
```suggestion
     *   - [[SortOrder.Asc]]: sets ascending sorting order
```

2023-04-20 13:26 UTC, drmarjanovic commented on modules/library/src/main/scala/zio/elasticsearch/query/sort/package.scala
> +     *   - [[SortOrder.Desc]]: sets Descending sorting order
```suggestion
     *   - [[SortOrder.Desc]]: sets descending sorting order
```

2023-04-20 14:06 UTC, drmarjanovic approved these changes

2023-04-20 14:06 UTC, merged