Support Newtype validation in Scala 2 and 3
lambdaworks/zio-elasticsearch pull request #165
Opened 2023-04-20 16:15 UTC by mvelimir

2023-04-20 17:40 UTC, drmarjanovic requested changes

2023-04-20 17:40 UTC, drmarjanovic commented on modules/library/src/main/scala-2/zio/elasticsearch/IndexNameValidation.scala
> +  private def containsAny(string: String, params: List[String]): Boolean =
Can we put this below public methods?

2023-04-20 17:40 UTC, drmarjanovic commented on modules/library/src/main/scala-2/zio/elasticsearch/ValidatedNewtypes.scala
> +    override def assertion = assertCustom { (string: String) => // scalafix:ok
Maybe use `name` also.

2023-04-20 17:40 UTC, drmarjanovic commented on modules/library/src/main/scala-3/zio/elasticsearch/IndexNameValidator.scala
> +    extends Validator[String](string => {
I would use `name` here as well.

2023-04-20 17:40 UTC, drmarjanovic commented on modules/library/src/main/scala-3/zio/elasticsearch/ValidatedNewtypes.scala
> +  object IndexName extends NewtypeCustom[String] {
Does it make sense to have separate objects for Index name and Routing. I would probably split this and remove `ValidatedNewtypes`.

2023-04-20 17:40 UTC, drmarjanovic commented on modules/library/src/main/scala-3/zio/elasticsearch/IndexNameValidator.scala
> +      if (!isValid(string)) {
Maybe we should use `if (isValid) Right(()) else ...`.

2023-04-20 17:40 UTC, drmarjanovic commented on modules/library/src/main/scala-2/zio/elasticsearch/ValidatedNewtypes.scala
> +      if (!IndexNameValidation.isValidIndexName(string)) {
Maybe to invert logic - `if (IndexNameValidation.isValidIndexName(...))`...

2023-04-21 06:54 UTC, arnoldlacko submitted a review, later dismissed

2023-04-21 07:16 UTC, dbulaja98 approved these changes

2023-04-21 08:34 UTC, drmarjanovic approved these changes

2023-04-21 08:34 UTC, merged