Support Max aggregation
lambdaworks/zio-elasticsearch pull request #195
Opened 2023-04-28 14:12 UTC by dbulaja98

2023-04-28 21:15 UTC, drmarjanovic requested changes

2023-04-28 21:15 UTC, drmarjanovic commented on modules/library/src/main/scala/zio/elasticsearch/aggregation/Aggregations.scala
> +final case class Max(name: String, field: String, missing: Option[Double]) extends MaxAggregation { self =>
Should this be private?

2023-04-28 21:15 UTC, drmarjanovic commented on modules/library/src/main/scala/zio/elasticsearch/aggregation/options/HasMissing.scala
> +   * Sets the `missing` parameter for the [[zio.elasticsearch.aggregation.ElasticAggregation]]. The`Missing` parameter
```suggestion
   * Sets the `missing` parameter for the [[zio.elasticsearch.aggregation.ElasticAggregation]]. The `missing` parameter
```

2023-04-30 09:37 UTC, arnoldlacko commented on modules/library/src/it/scala/zio/elasticsearch/HttpExecutorSpec.scala
> +          test("aggregate using terms aggregation with nested max aggregation") {
Is this meant to be replacing the `terms` test, do we not want to keep both?

2023-04-30 09:39 UTC, arnoldlacko commented on modules/library/src/it/scala/zio/elasticsearch/HttpExecutorSpec.scala
> +          test("aggregate using terms aggregation with nested max aggregation") {
I see the point, it's nesting aggregations of different type.

2023-05-02 16:54 UTC, drmarjanovic approved these changes

2023-05-02 17:00 UTC, merged