Replace List with Chunk
lambdaworks/zio-elasticsearch pull request #215
Opened 2023-05-11 10:38 UTC by mvelimir

2023-05-11 11:04 UTC, dbulaja98 approved these changes

2023-05-11 11:17 UTC, markaya requested changes

2023-05-11 11:17 UTC, markaya commented on modules/library/src/main/scala/zio/elasticsearch/result/ElasticResult.scala
> +  lazy val items: UIO[List[Item]] = ZIO.succeed(hits.toList)
Why we don't return UIO[Chunk[Item]]?

2023-05-11 11:17 UTC, markaya commented on modules/library/src/main/scala/zio/elasticsearch/result/ElasticResult.scala
>    def documentAs[A: Schema]: Task[List[A]] =
Same here, Task[Chunk[A]]

2023-05-11 11:17 UTC, markaya commented on modules/library/src/main/scala/zio/elasticsearch/result/Item.scala
>    def innerHitAs[A](name: String)(implicit schema: Schema[A]): Either[DecodingException, List[A]] =
Can we return Either[DecodingException, Chunk[A]] here?

2023-05-12 16:26 UTC, markaya approved these changes

2023-05-14 00:26 UTC, drmarjanovic approved these changes

2023-05-14 00:26 UTC, merged