(dsl): Support 'BucketSelector' aggregation
lambdaworks/zio-elasticsearch pull request #217
Opened 2023-05-11 12:40 UTC by dbulaja98

2023-05-11 14:13 UTC, markaya requested changes

2023-05-11 14:13 UTC, markaya commented on modules/library/src/it/scala/zio/elasticsearch/HttpExecutorSpec.scala
> +            "search using match all query with terms aggregations with nested max aggregation and bucketSelector aggregation"
```suggestion
            "search using match all query with terms aggregations, nested max aggregation and nested bucketSelector aggregation"
```

2023-05-11 15:03 UTC, drmarjanovic submitted a review, later dismissed

2023-05-12 09:40 UTC, drmarjanovic approved these changes

2023-05-12 09:40 UTC, merged