Add `boost` to MatchPhrase, Exists and HasParent query
lambdaworks/zio-elasticsearch pull request #229
Opened 2023-05-25 22:20 UTC by dbulaja98

2023-05-25 23:26 UTC, drmarjanovic requested changes
Do you need to update website docs as well?

2023-05-25 23:26 UTC, drmarjanovic commented on modules/library/src/test/scala/zio/elasticsearch/ElasticQuerySpec.scala
> +          val queryTsWithBoost = exists(TestDocument.intField).boost(3)
You can use `queryWithBoost`.

2023-05-26 06:13 UTC, markaya requested changes

2023-05-26 15:49 UTC, drmarjanovic approved these changes

2023-05-26 16:24 UTC, markaya approved these changes

2023-05-26 16:25 UTC, merged