(dsl) Support geopolygon query
lambdaworks/zio-elasticsearch pull request #264
Opened 2023-06-24 12:22 UTC by LeonaNedeljkovic

2023-06-24 12:25 UTC, markaya commented on modules/library/src/main/scala/zio/elasticsearch/ElasticQuery.scala
> +
Remove one empty line

2023-06-24 12:55 UTC, drmarjanovic requested changes

2023-06-24 12:55 UTC, drmarjanovic commented on modules/library/src/main/scala/zio/elasticsearch/query/Queries.scala
> +          queryName.map(qn => "_name" -> qn.toJson),
Let's use `queryName.map("_name" -> _.toJson)`.

2023-06-24 12:55 UTC, drmarjanovic commented on modules/library/src/main/scala/zio/elasticsearch/query/Queries.scala
> +          validationMethod.map(vm => "validation_method" -> vm.toString.toJson)
Let's use `validationMethod.map("validation_method" -> _.toString.toJson)`.

2023-06-24 12:55 UTC, drmarjanovic commented on modules/library/src/test/scala/zio/elasticsearch/ElasticQuerySpec.scala
> +          assert(queryString)(
Should we move this in the row above?

2023-06-24 12:55 UTC, drmarjanovic commented on modules/library/src/test/scala/zio/elasticsearch/ElasticQuerySpec.scala
> +          println(queryWithName.toJson(fieldPath = None))
Please remove `println`.

2023-06-24 13:31 UTC, dbulaja98 requested changes

2023-06-24 13:31 UTC, dbulaja98 commented on modules/library/src/main/scala/zio/elasticsearch/query/Queries.scala
> +   *   the [[String]] value to represent the name field
```suggestion
   *   the text value to represent the name field
```

2023-06-24 13:31 UTC, dbulaja98 commented on modules/library/src/main/scala/zio/elasticsearch/query/Queries.scala
> +  def name(value: String): GeoPolygonQuery[S] = self.copy(queryName = Some(value))
Move `self.copy(queryName = Some(value))` to new line.

2023-06-24 14:23 UTC, markaya submitted a review, later dismissed

2023-06-24 14:44 UTC, dbulaja98 approved these changes

2023-06-24 15:04 UTC, markaya commented on modules/library/src/it/scala/zio/elasticsearch/HttpExecutorSpec.scala
> +              } yield assertTrue(r1 == Chunk(document))
```suggestion
              } yield assert(equalTo(Chunk(document)))
```

2023-06-24 18:52 UTC, drmarjanovic approved these changes

2023-06-28 09:20 UTC, dbulaja98 submitted a review, later dismissed

2023-09-26 10:17 UTC, drmarjanovic commented
@LeonaNedeljkovic, are you still working on this? Is there anything that's blocking you?

2023-12-18 15:51 UTC, dbulaja98 requested changes

2023-12-18 15:51 UTC, dbulaja98 commented on modules/library/src/main/scala/zio/elasticsearch/query/Queries.scala
> +  points: List[String],
Can you replace `List[String]` with `Chunk[String]`?

2023-12-18 15:51 UTC, dbulaja98 commented on modules/library/src/test/scala/zio/elasticsearch/ElasticQuerySpec.scala
> +          val queryString =
```suggestion
          val queryTs =
```

2023-12-18 15:51 UTC, dbulaja98 commented on modules/library/src/test/scala/zio/elasticsearch/ElasticQuerySpec.scala
> +          val queryString =
```suggestion
          val queryTs =
```

2023-12-18 15:51 UTC, dbulaja98 commented on modules/library/src/test/scala/zio/elasticsearch/ElasticQuerySpec.scala
> +          val expectedWithString =
```suggestion
          val expectedTs =
```

2023-12-18 15:51 UTC, dbulaja98 commented on docs/overview/queries/elastic_query_geo_polygon.md
> +
Omit one empty line.

2023-12-21 12:42 UTC, dbulaja98 approved these changes

2023-12-21 13:06 UTC, merged