(dsl): Support `refresh` request
lambdaworks/zio-elasticsearch pull request #300
Opened 2023-08-14 11:07 UTC by milicns

This PR resolves #262

2023-08-14 11:26 UTC, dbulaja98 requested changes

2023-08-14 11:26 UTC, dbulaja98 commented on docs/overview/requests/elastic_request_refresh.md
> +This request refresh one or more Elasticsearch indices.
Maybe: This request is used for refreshing ...?

2023-08-14 11:26 UTC, dbulaja98 commented on docs/overview/requests/elastic_request_refresh.md
> +
Omit one empty line.

2023-08-14 11:26 UTC, dbulaja98 commented on modules/integration/src/test/scala/zio/elasticsearch/HttpExecutorSpec.scala
> +          test("return 'NotFound' if index does not exists") {
```suggestion
          test("return false if index does not exists") {
```

2023-08-14 11:26 UTC, dbulaja98 commented on modules/library/src/main/scala/zio/elasticsearch/ElasticRequest.scala
> +   * Constructs an instance of [[RefreshRequest]] used for deleting an index by specified name.
Update this scaladoc.

2023-08-14 11:26 UTC, dbulaja98 commented on modules/library/src/test/scala/zio/elasticsearch/HttpElasticExecutorSpec.scala
> +            )
Can this be in one line?

2023-08-14 13:40 UTC, dbulaja98 commented on modules/library/src/main/scala/zio/elasticsearch/ElasticRequest.scala
> +   * Constructs an instance of [[RefreshRequest]] used for refreshing an index by specified name.
```suggestion
   * Constructs an instance of [[RefreshRequest]] used for refreshing an index with specified name.
```

2023-08-14 15:19 UTC, dbulaja98 approved these changes

2023-08-15 07:48 UTC, dbulaja98 requested changes

2023-08-15 07:48 UTC, dbulaja98 commented on docs/overview/requests/elastic_request_refresh.md
> +You can find more information about `Refresh` request [here](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/indices-refresh.html).
Put empty line here.

2023-08-15 13:41 UTC, petarcurcin requested changes

2023-08-15 13:41 UTC, petarcurcin commented on modules/library/src/main/scala/zio/elasticsearch/executor/HttpExecutor.scala
> +  private final val Refresh       = "_refresh"
Put this in right order.

2023-08-15 15:57 UTC, petarcurcin approved these changes

2023-08-15 20:20 UTC, merged