(dsl): Support `matchPhrasePrefix` query
lambdaworks/zio-elasticsearch pull request #301
Opened 2023-08-14 15:07 UTC by milicns

Part of #91

2023-08-15 08:17 UTC, dbulaja98 requested changes

2023-08-15 08:17 UTC, dbulaja98 commented on modules/library/src/main/scala/zio/elasticsearch/query/Queries.scala
> +}
Put empty line between.

2023-08-15 08:17 UTC, dbulaja98 commented on modules/library/src/test/scala/zio/elasticsearch/ElasticQuerySpec.scala
> +          )
Can this be in one line?

2023-08-16 07:27 UTC, dbulaja98 submitted a review, later dismissed

2023-08-16 09:26 UTC, dbulaja98 approved these changes

2023-08-16 10:42 UTC, petarcurcin approved these changes

2023-08-17 12:47 UTC, merged