(dsl): Support `matchBooleanPrefix` query
lambdaworks/zio-elasticsearch pull request #304
Opened 2023-08-15 15:02 UTC by milicns

Part of #91

2023-08-21 19:03 UTC, dbulaja98 requested changes

2023-08-21 19:03 UTC, dbulaja98 commented on modules/integration/src/test/scala/zio/elasticsearch/HttpExecutorSpec.scala
> +          test("search for a document using a match boolean prefix query") {
Write just one it-test for this query. There is no need to check `minimumShouldMatch` only.

2023-08-22 19:07 UTC, drmarjanovic requested changes

2023-08-22 19:07 UTC, drmarjanovic commented on docs/overview/queries/elastic_query_match_boolean_prefix.md
> +
Unnecessary new line.

2023-08-22 19:07 UTC, drmarjanovic commented on modules/library/src/test/scala/zio/elasticsearch/ElasticQuerySpec.scala
> +        test("matchBooleanPrefix") {
Move this between `matchAll` and `matches`.

2023-08-22 19:07 UTC, drmarjanovic commented on modules/library/src/test/scala/zio/elasticsearch/ElasticQuerySpec.scala
> +        test("matchBooleanPrefix") {
Move this between `matchAll` and `matches`.

2023-08-23 20:20 UTC, dbulaja98 approved these changes
Nice job!

2023-08-23 20:20 UTC, merged