(dsl): Support `constantScore` query
lambdaworks/zio-elasticsearch pull request #307
Opened 2023-08-21 13:12 UTC by milicns

Part of #64

2023-08-22 19:18 UTC, drmarjanovic requested changes

2023-08-22 19:18 UTC, drmarjanovic commented on docs/overview/queries/elastic_query_constant_score.md
> +
Unnecessary new line.

2023-08-23 21:51 UTC, dbulaja98 requested changes

2023-08-23 21:51 UTC, dbulaja98 commented on docs/overview/queries/elastic_query_constant_score.md
> +You can create a [type-safe](https://lambdaworks.github.io/zio-elasticsearch/overview/overview_zio_prelude_schema) `ConstantScore` query with arbitrary query(`MatchPhrase` in this example) using the
```suggestion
You can create a [type-safe](https://lambdaworks.github.io/zio-elasticsearch/overview/overview_zio_prelude_schema) `ConstantScore` query with arbitrary [type-safe](https://lambdaworks.github.io/zio-elasticsearch/overview/overview_zio_prelude_schema) query(`MatchPhrase` in this example) using the `constantScore` method in the following manner:
```

2023-08-23 21:51 UTC, dbulaja98 commented on docs/overview/queries/elastic_query_constant_score.md
> +val queryWithBoost: ConstantScoreQuery = constantScore(matchPhrase(field = Document.name, value ="test")).boost(2.2)
```suggestion
val queryWithBoost: ConstantScoreQuery = constantScore(matchPhrase(field = Document.name, value = "test")).boost(2.2)
```

2023-08-23 21:51 UTC, dbulaja98 commented on modules/integration/src/test/scala/zio/elasticsearch/HttpExecutorSpec.scala
> +                } yield assert(res)(Assertion.contains(document))
Add if possible: `assert(res)(!Assertion.contains(secondDocumentId)`.

2023-08-23 21:51 UTC, dbulaja98 commented on modules/library/src/main/scala/zio/elasticsearch/ElasticQuery.scala
> +   *   query you wish to run
Maybe something like this:

query to be wrapped inside of constant score query? Or something similar.

2023-08-23 21:51 UTC, dbulaja98 commented on modules/library/src/main/scala/zio/elasticsearch/ElasticQuery.scala
> +   *   document for which field query is executed. An implicit `Schema` instance must be in scope
Maybe
```suggestion
   *   document for which field query is specified for. An implicit `Schema` instance must be in scope
```?

2023-08-23 21:51 UTC, dbulaja98 commented on modules/library/src/main/scala/zio/elasticsearch/ElasticQuery.scala
> +   *   that must satisfy the criteria.
```suggestion
   *   an instance of [[zio.elasticsearch.query.ConstantScoreQuery]] that represents the constant score query with query
   *   that must satisfy the criteria to be performed.
```

2023-08-23 21:51 UTC, dbulaja98 commented on modules/library/src/main/scala/zio/elasticsearch/ElasticQuery.scala
> +    ConstantScore[S](query, boost = None)
Name first parameter.

2023-08-23 21:51 UTC, dbulaja98 commented on modules/library/src/main/scala/zio/elasticsearch/ElasticQuery.scala
> +    ConstantScore[Any](query, boost = None)
Name first parameter.

2023-08-23 21:51 UTC, dbulaja98 commented on modules/library/src/main/scala/zio/elasticsearch/ElasticQuery.scala
> +   *   query you wish to run
Same as above.

2023-08-23 21:51 UTC, dbulaja98 commented on modules/library/src/main/scala/zio/elasticsearch/ElasticQuery.scala
> +   *   that must satisfy the criteria.
Same as above.

2023-08-23 21:51 UTC, dbulaja98 commented on modules/library/src/main/scala/zio/elasticsearch/query/Queries.scala
> +  def boost(value: Double): ConstantScoreQuery[S] =
Put empty line between.

2023-08-23 21:51 UTC, dbulaja98 commented on modules/library/src/test/scala/zio/elasticsearch/ElasticQuerySpec.scala
> +        test("constantScore") {
Some parameters are named, some are not.

2023-08-28 11:56 UTC, dbulaja98 commented on modules/library/src/main/scala/zio/elasticsearch/ElasticQuery.scala
> +   *   document for which field query is specified for. An implicit `Schema` instance must be in scope
```suggestion
   *   document for which field query is specified for. An implicit `Schema` instance must be provided in the scope
```

2023-08-29 08:34 UTC, merged