(dsl): Support Weight Avg aggregation
lambdaworks/zio-elasticsearch pull request #358
Opened 2023-11-08 13:42 UTC by vanjaftn

2023-11-09 22:24 UTC, dbulaja98 commented on docs/overview/aggregations/elastic_aggregation_weighted_avg.md
> +val multipleAggregations: MultipleAggregations = weightedAvgAggregation(name = "weightedAvgAggregation", valueField = Document.intField, weightField = Document.doubleField).withAgg(weightedAvgAggrega
Can you give them different names?

2023-11-09 22:24 UTC, dbulaja98 commented on docs/overview/aggregations/elastic_aggregation_weighted_avg.md
> +val aggregationWithMissing: WeightedAvgAggregation = weightedAvgAggregation(name = "weightedAvgAggregation", field = Document.intField).valueMissing(10.0)
```suggestion
val aggregationWithValueMissing: WeightedAvgAggregation = weightedAvgAggregation(name = "weightedAvgAggregation", field = Document.intField).valueMissing(10.0)
```

2023-11-09 22:24 UTC, dbulaja98 commented on docs/overview/aggregations/elastic_aggregation_weighted_avg.md
> +val aggregationWithMissing: WeightedAvgAggregation = weightedAvgAggregation(name = "weightedAvgAggregation", field = Document.intField).weightMissing(5.0)
```suggestion
val aggregationWithWeightMissing: WeightedAvgAggregation = weightedAvgAggregation(name = "weightedAvgAggregation", field = Document.intField).weightMissing(5.0)
```

2023-11-09 22:25 UTC, dbulaja98 commented on docs/overview/aggregations/elastic_aggregation_weighted_avg.md
> +val aggregationWithMissing: WeightedAvgAggregation = weightedAvgAggregation(name = "weightedAvgAggregation", field = Document.intField).weightMissing(10.0).valueMissing(5.0)
```suggestion
val aggregationWithValueAndWeightMissing: WeightedAvgAggregation = weightedAvgAggregation(name = "weightedAvgAggregation", field = Document.intField).weightMissing(10.0).valueMissing(5.0)
```

2023-11-09 22:30 UTC, dbulaja98 commented on modules/library/src/main/scala/zio/elasticsearch/ElasticAggregation.scala
> +   *   the type-safe field for weight for which weighted avg aggregation will be executed
Maybe something like this:
```suggestion
   *   the type-safe field that represents weight for which weighted avg aggregation will be executed
```

2023-11-09 22:30 UTC, dbulaja98 commented on modules/library/src/main/scala/zio/elasticsearch/ElasticAggregation.scala
> +   *   the type-safe field for weight for which weighted avg aggregation will be executed
Something like this for `valueField` also.

2023-11-09 22:31 UTC, dbulaja98 commented on modules/library/src/main/scala/zio/elasticsearch/ElasticAggregation.scala
> +      weightField = weightField.toString,
Reorder this, put optional parameters at the end.

2023-11-09 22:31 UTC, dbulaja98 commented on modules/library/src/main/scala/zio/elasticsearch/ElasticAggregation.scala
> +   *   the field for weight for which weighted avg aggregation will be executed
Same here.

2023-11-09 22:31 UTC, dbulaja98 commented on modules/library/src/main/scala/zio/elasticsearch/ElasticAggregation.scala
> +      weightMissing = None
Reorder this also.

2023-11-09 22:38 UTC, dbulaja98 commented on modules/library/src/main/scala/zio/elasticsearch/aggregation/Aggregations.scala
> +  weightMissing: Option[Double]
Put option parameters at the end.

2023-11-09 22:39 UTC, dbulaja98 commented on modules/library/src/main/scala/zio/elasticsearch/aggregation/Aggregations.scala
> +  def withAgg(agg: SingleElasticAggregation): MultipleAggregations =
Reorder methods.

2023-11-09 22:39 UTC, dbulaja98 commented on modules/library/src/main/scala/zio/elasticsearch/aggregation/Aggregations.scala
> +
Omit empty line.

2023-11-09 22:39 UTC, dbulaja98 commented on modules/library/src/main/scala/zio/elasticsearch/aggregation/Aggregations.scala
> +
Omit empty line.

2023-11-09 22:52 UTC, dbulaja98 commented on modules/library/src/main/scala/zio/elasticsearch/executor/response/SearchWithAggregationsResponse.scala
> +                      WeightedAvgAggregationResponse.decoder.decodeJson(data.toString).map(field.split("#")(1) -> _)
Put this first and remove `&& !str.contains("weighted_avg#")` from the first case.

2023-11-09 22:54 UTC, dbulaja98 commented on modules/library/src/test/scala/zio/elasticsearch/ElasticAggregationSpec.scala
> +          val aggregationWithBothMissing = weightedAvgAggregation(
```suggestion
          val aggregationWithValueAndWeightMissing = weightedAvgAggregation(
```

2023-11-09 22:56 UTC, dbulaja98 commented on modules/library/src/test/scala/zio/elasticsearch/ElasticAggregationSpec.scala
> +          val aggregationWithBothMissing = weightedAvgAggregation(
Same.

2023-11-12 13:59 UTC, dbulaja98 requested changes

2023-11-13 08:14 UTC, vanjaftn commented on docs/overview/aggregations/elastic_aggregation_weighted_avg.md
> +The `Weighted Avg` aggregation is a single-value metrics aggregation that computes the average while taking into account the varying degrees of importance of numeric values. As a formula, a weighted
Isn't "weighted" or "taking into account the varying degrees of importance of numeric values" unnecessary because they mean the same thing?

2023-11-13 14:33 UTC, dbulaja98 approved these changes

2023-11-13 14:33 UTC, merged